language: java
jdk:
    - oraclejdk8
before_cache:
    - rm -rf $HOME/.gradle/caches/jars-1/jars-1.lock
    - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
        - $HOME/.gradle/wrapper
        - $HOME/.gradle/caches/jars-1
        - $HOME/.gradle/caches/modules-2
        - $HOME/.gradle/caches/2.6
